### ISSUE TITLE
Stop the DelayedProgressDialog to disappear when clicking outside?

### ISSUE THREAD

**Issue by rohitguptanm** [Q115/DelayedProgressDialog#2]
How to stop the DelayedProgressDialog to disappear when clicking outside?

I tried below the line in onCreateDialog(). but not worked

`builder.setCancelable(false);`

` public Dialog onCreateDialog(Bundle savedInstanceState) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        LayoutInflater inflater = getActivity().getLayoutInflater();
        builder.setView(inflater.inflate(R.layout.dialog_progress, null));
        builder.setCancelable(false);
        return builder.create();
    }`

**Comment by Q115** [comment]
setCancelable(false);

will work.

```
 public Dialog onCreateDialog(Bundle savedInstanceState) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.ProgressDialogNoBackgroundStyle);
        LayoutInflater inflater = getActivity().getLayoutInflater();
        setCancelable(false);
        builder.setView(inflater.inflate(R.layout.dialog_progress, null));
        return builder.create();
    }
```

**Comment by rohitguptanm** [comment]
Thanks, bro... I didn't notice this class itself is DialogFragment. so it has own method setCancelable. thanks for the help.
